Remove build command
manala/manalize pull request #33
Opened 2016-10-02 16:20 UTC by chalasr

The first motivation for having this command was to have a better control over the VM provisioning,  a better error catching and a better behavior in case of fail, with btw a nice output.

However, it would be so hard to maintain for not much value.
So let's stay focused on the `setup` which is the main feature of this tool, lots of nice stuff can (and have to) be done on this part.

2016-10-02 16:34 UTC, ogizanagi commented
The `README.md` should be updated as well.

But let's wait for @nervo and @hyvs opinions about this. Maybe they have something else in mind that could live inside the `manala/manala` repository and bring enough value without being redondant with the manala roles config.

2016-10-02 19:40 UTC, nervo commented
Ready to discuss tomorow morning :)

2016-10-05 16:22 UTC, ogizanagi requested changes

2016-10-05 16:22 UTC, ogizanagi commented on src/Exception/HandlingFailureException.php
> -class HandlingFailureException extends \RuntimeException
This one is to keep (used by `Diff` and should probably be added to the `@throws` docblock section of [`Manala\Handler\Handler::handle()`](https://github.com/manala/manala/blob/master/src/Handler/Handler.php#L30))

2016-10-05 16:23 UTC, chalasr commented on src/Exception/HandlingFailureException.php
> -class HandlingFailureException extends \RuntimeException
Good catch

2016-10-05 22:05 UTC, chalasr commented on src/Exception/HandlingFailureException.php
> -class HandlingFailureException extends \RuntimeException
Fixed

2016-10-05 22:09 UTC, ogizanagi approved these changes

2016-10-05 22:09 UTC, chalasr commented
The naming has changed in the `manala.yml` mapping, now it contains two targets `setup` and `install`, both have placeholders in the makefile, replaced at manalizing.

The `BuildTest` (now calling `make setup`) is green.

2016-10-05 22:11 UTC, chalasr commented on src/Resources/symfony/manala.yml
> +        - if [ -d  "./var/cache" ]; then rm -rf ./var/cache && mkdir ./var/cache; fi;
This is a workaround mandatory until @nervo automagically dumps all the files from these directories into a temp dir then redump them after provisioning (I have not the heart to write such in the makefile, this is already so ugly)

2016-10-05 22:13 UTC, chalasr commented on src/Resources/symfony/manala.yml
> +        - if [ -d  "./var/cache" ]; then rm -rf ./var/cache && mkdir ./var/cache; fi;
Here is the error output:

> fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "gid": 20, "group": "dialout", "mode": "0755", "msg": "the directory /srv/app/var/logs is not empty, refusing to convert it", "owner": "501", "path": "/srv/app/var/logs", "size": 102, "state": “directory”

2016-10-05 22:16 UTC, ogizanagi requested changes
Don't forget to remove the usage in `README.md` :)

2016-10-05 22:16 UTC, ogizanagi commented on src/Env/EnvFactory.php
> +     * @return Env
the whole docblock can be removed (was removed in #40 btw)

2016-10-05 22:18 UTC, ogizanagi approved these changes

2016-10-05 22:21 UTC, chalasr commented on src/Resources/symfony/manala.yml
> +make_targets:
Note that this allows to have only one generic makefile. Most of the targets that aren't in this yaml file are not specific to the env type at all.

2016-10-05 22:23 UTC, merged